<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Logica\Logica.csproj" />
    <ProjectReference Include="..\Entidades\Entidades.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Presentacion</RootNamespace>
    <AssemblyName>SGAPE</AssemblyName>
    <Version>1.0.0</Version>
    <Product>SGAPE</Product>
    <Company>Universidad Popular del Cesar</Company>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
  </PropertyGroup>

</Project>